// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pricing.Infrastructure.Persistence;

#nullable disable

namespace Pricing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260426184430_SyncCourtOverrideMapping")]
    partial class SyncCourtOverrideMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pricing.Domain.Entities.PriceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.ToTable("PriceRules", "pricing");
                });

            modelBuilder.Entity("Pricing.Domain.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BaseHourlyRate", "Pricing.Domain.Entities.Tariff.BaseHourlyRate#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BaseHourlyRate");
                        });

                    b.HasKey("Id");

                    b.ToTable("Tariffs", "pricing");
                });

            modelBuilder.Entity("Pricing.Domain.Entities.PriceRule", b =>
                {
                    b.HasOne("Pricing.Domain.Entities.Tariff", null)
                        .WithMany("PriceRules")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pricing.Domain.Entities.Tariff", b =>
                {
                    b.OwnsMany("Pricing.Domain.Entities.CourtRateOverride", "CourtRateOverrides", b1 =>
                        {
                            b1.Property<Guid>("TariffId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CourtId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("HourlyRate")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("HourlyRate");

                            b1.HasKey("TariffId", "CourtId");

                            b1.ToTable("CourtRateOverrides", "pricing");

                            b1.WithOwner()
                                .HasForeignKey("TariffId");
                        });

                    b.Navigation("CourtRateOverrides");
                });

            modelBuilder.Entity("Pricing.Domain.Entities.Tariff", b =>
                {
                    b.Navigation("PriceRules");
                });
#pragma warning restore 612, 618
        }
    }
}
